
// This file has been generated by the GUI designer. Do not modify.
namespace janpGui
{
	public partial class mariella
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Button btnExit;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget janpGui.mariella
			this.Name = "janpGui.mariella";
			this.Title = global::Mono.Unix.Catalog.GetString("mariella");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child janpGui.mariella.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnExit = new global::Gtk.Button();
			this.btnExit.CanFocus = true;
			this.btnExit.Name = "btnExit";
			this.btnExit.UseUnderline = true;
			this.btnExit.Label = global::Mono.Unix.Catalog.GetString("Exit");
			this.fixed3.Add(this.btnExit);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnExit]));
			w1.X = 304;
			w1.Y = 215;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.btnExit.Clicked += new global::System.EventHandler(this.btnClick);
		}
	}
}
